[package]
name = "cursive-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0", features = ["derive"] }
cursive = "0.16"
env_logger = "0.9"
log = "0.4"
